; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = ${PROJECT_DIR}
default_envs = nano_atmega328pb_arduino

[env]
platform = atmelavr
framework = arduino

[env:uno]
board = uno
lib_extra_dirs = ~/Documents/Arduino/libraries
monitor_port = /dev/ttyACM0
monitor_speed = 9600

[env:nano_normal]
board = nanoatmega328
lib_extra_dirs = ~/Documents/Arduino/libraries

monitor_port = /dev/ttyUSB0
monitor_speed = 9600

[env:nano_atmega328pb_serial]
board = nanoatmega328
lib_extra_dirs = ~/Documents/Arduino/libraries
board_build.f_cpu = 16000000L
; Override the upload command to force AVRDUDE to see it as a 328PB
upload_protocol = custom
upload_port = /dev/ttyUSB0
upload_flags =
    -C
    ~/Tools/avrdude_Linux_64bit/etc/avrdude.conf
    -p
    atmega328pb
    -c
    urclock
    -b
    ${env:nano_atmega328pb_fuses_bootloader.board_bootloader.speed}
    -P
    $UPLOAD_PORT

upload_command = ~/Tools/avrdude_Linux_64bit/bin/avrdude $UPLOAD_FLAGS -U flash:w:$SOURCE:i

monitor_port = /dev/ttyUSB0
monitor_speed = 9600

; Run the following command to upload with this environment
; pio run -e Upload_UART -t upload
[env:nano_atmega328pb_arduino]
board = nanoatmega328
lib_extra_dirs = ~/Documents/Arduino/libraries
board_build.f_cpu = 16000000L

upload_protocol = custom
upload_port = /dev/ttyUSB0
upload_flags =
    -C
    ~/Tools/avrdude_Linux_64bit/etc/avrdude.conf
    -p
    atmega328p
    -c
    arduino
    -b
    ${env:nano_atmega328pb_fuses_bootloader.board_bootloader.speed}
    -P
    $UPLOAD_PORT

upload_command = ~/Tools/avrdude_Linux_64bit/bin/avrdude $UPLOAD_FLAGS -U flash:w:$SOURCE:i

monitor_port = /dev/ttyUSB0
monitor_speed = 9600

; Run the following command to set fuses
; pio run -e fuses_bootloader -t fuses
; Run the following command to set fuses + burn bootloader
; pio run -e fuses_bootloader -t bootloader
[env:nano_atmega328pb_fuses_bootloader]
board = ATmega328PB
lib_extra_dirs = ~/Documents/Arduino/libraries
board_build.f_cpu = 16000000L
build_unflags = -flto
build_flags = 
board_hardware.oscillator = external
board_bootloader.type = urboot
board_bootloader.speed = 115200
board_hardware.uart = uart0
board_hardware.bod = 2.7v
board_hardware.eesave = yes
upload_protocol = usbasp
upload_flags = 
	-PUSB
	-B8
